version: "2"
services:
  app:
    image: flask
    restart: unless-stopped
    networks:
      orientation:
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      orientation:
  redis:
    restart: unless-stopped
    image: redis
    networks:
      orientation:
networks:
  orientation:
