version: "2"
services:
  app:
    image: clemenko/orient_flask
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: unless-stopped
  redis:
    restart: unless-stopped
    image: redis
