version: "3.1"
services:
  app:
    image: clemenko/flask_demo
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        #failure_action: rollback
      mode: replicated
      placement:
        constraints:
          - 'node.role == worker'
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
      labels:
          com.docker.ucp.access.label: "prod"
          com.docker.ucp.mesh.http.5000: "external_route=http://flask.dockr.life,internal_port=5000"
    networks:
      db:
      kv:
      ucp-hrm:
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
    secrets:
      - source: demo_title_v1
        target: demo_title
        uid: "0"
        gid: "0"
        mode: 0400


  mongo:
    image: mongo
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      db:

  redis:
    image: redis
    deploy:
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      kv:


networks:
  kv:
  db:
#    driver: overlay
#    driver_opts:
#    encrypted: 'yes'
  ucp-hrm:
    external: true

secrets:
  demo_title_v1:
    external: true
