version: "3.2"
services:
  traefik:
    image: traefik
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - 'node.role == manager'
    ports:
      - 443:443
      - 8080:8080
    networks:
      inbound:
    command: --docker --docker.swarmmode --docker.domain=app.dockr.life --docker.watch --web --accesslogsfile=/dev/stdout --entryPoints="Name:https Address::443 TLS:/ssl/cert.pem,/ssl/key.pem" --defaultentrypoints="https" --debug

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/certs/:/ssl/
networks:
  inbound:
