version: "3.2"
services:
  flask:
    image: clemenko/akamai_demo
    deploy:
      replicas: 10
      mode: replicated
      labels:
        com.docker.ucp.access.label: "prod"
        - 'traefik.port=5000'
        - 'traefik.frontend.rule=Host:flask.dockr.life'
        - 'traefik.docker.network=traefik_inbound'
        - 'traefik.backend.loadbalancer.sticky=true'
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      db:
      kv:
      traefik_inbound:
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  whoami:
    image: emilevauge/whoami
    deploy:
      replicas: 5
      mode: replicated
      labels:
        com.docker.ucp.access.label: "prod"
        - 'traefik.port=80'
        - 'traefik.frontend.rule=Host:app.dockr.life; PathPrefixStrip: /whoami/'
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      traefik_inbound:

  mongo:
    image: mongo
    deploy:
      labels:
        com.docker.ucp.access.label: "prod"
    networks:
      db:

  redis:
    image: redis
    deploy:
      labels:
        com.docker.ucp.access.label: "prod"
    networks:
      kv:

networks:
  kv:
    labels:
      com.docker.ucp.access.label: "prod"
  db:
    labels:
      com.docker.ucp.access.label: "prod"
  traefik_inbound:
    external: true
